env:
  browser: true
  es2021: true
extends:
  - plugin:react/recommended
  - airbnb
parserOptions:
  ecmaFeatures:
    jsx: true
  ecmaVersion: latest
  sourceType: module
plugins:
  - react
rules:
  react/jsx-one-expression-per-line: "off"
  no-nested-ternary: "off"
  max-len:
    - 'error'
    - code: 150
