FROM ruby:2.4.0

# app dependencies
RUN apt-get update -qq && apt-get install -y build-essential libpq-dev nodejs

ENV RAILS_ENV=development \
    APP_HOME=/usr/src/app

RUN mkdir $APP_HOME
WORKDIR $APP_HOME
