
blank_issues_enabled: false
contact_links:
  - name: Greenlight Setup
    url: https://groups.google.com/g/bigbluebutton-greenlight
    about: Get help with the installation, setup and configuration of Greenlight.
