externalSecret:
  enabled: true
  backendType: secretsManager
  data: []
  dataFrom:
    - greenlight
  env:
    - BIGBLUEBUTTON_ENDPOINT
    - BIGBLUEBUTTON_SECRET
    - DB_ADAPTER
    - DB_HOST
    - DB_NAME
    - DB_PASSWORD
    - DB_PORT
    - DB_USERNAME
    - SECRET_KEY_BASE
    - SMTP_AUTH
    - SMTP_DOMAIN
    - SMTP_PASSWORD
    - SMTP_PORT
    - SMTP_SENDER
    - SMTP_SERVER
    - SMTP_STARTTLS_AUTO
    - SMTP_TEST_RECIPIENT
    - SMTP_USERNAME
    - WEB_CONCURRENCY

containerPort: 80

resources:
  limits:
    cpu: 1000m
    memory: 2048Mi
  requests:
    cpu: 100m
    memory: 300Mi

autoscaling:
  enabled: true
  minReplicas: 1
  maxReplicas: 2
  targetCPUUtilizationPercentage: 80

nodeSelector:
  kubernetes.io/arch: amd64
  node/namespace: adedge

livenessProbe:
  httpGet:
    path: /b/health_check
    port: http
  timeoutSeconds: 12
  initialDelaySeconds: 60
  periodSeconds: 60

readinessProbe:
  httpGet:
    path: /b/health_check
    port: http
  timeoutSeconds: 12
  initialDelaySeconds: 60
  periodSeconds: 60

startupProbe:
  httpGet:
    path: /b/health_check
    port: http
  timeoutSeconds: 12
  initialDelaySeconds: 90
  failureThreshold: 5
  periodSeconds:  60

datadog:
  logs:
    enabled: true
