externalSecret:
  enabled: true
  backendType: secretsManager
  data: []
  dataFrom:
    - greenlight
  env:
    - BIGBLUEBUTTON_ENDPOINT
    - BIGBLUEBUTTON_SECRET
    - DB_ADAPTER
    - DB_HOST
    - DB_NAME
    - DB_PASSWORD
    - DB_PORT
    - DB_USERNAME
    - SECRET_KEY_BASE
    - SMTP_AUTH
    - SMTP_DOMAIN
    - SMTP_PASSWORD
    - SMTP_PORT
    - SMTP_SENDER
    - SMTP_SERVER
    - SMTP_STARTTLS_AUTO
    - SMTP_TEST_RECIPIENT
    - SMTP_USERNAME
    - WEB_CONCURRENCY
    - MAX_GREENLIGHT_USERS

containerPort: 80

resources:
  limits:
    cpu: 1000m
    memory: 2048Mi
  requests:
    cpu: 100m
    memory: 300Mi

autoscaling:
  enabled: true
  minReplicas: 1
  maxReplicas: 3
  targetCPUUtilizationPercentage: 80

nodeSelector:
  kubernetes.io/arch: amd64
  node/namespace: adedge

livenessProbe:
  httpGet:
    path: /b/health_check
    port: http
  timeoutSeconds: 15
  initialDelaySeconds: 15
  periodSeconds: 30

readinessProbe:
  httpGet:
    path: /b/health_check
    port: http
  timeoutSeconds: 15
  initialDelaySeconds: 15
  periodSeconds: 30

startupProbe:
  httpGet:
    path: /b/health_check
    port: http
  timeoutSeconds: 15
  initialDelaySeconds: 30
  failureThreshold: 5
  periodSeconds:  30

initContainers:
  - name: db-start-up-checker-service
    image: 065145189516.dkr.ecr.us-east-1.amazonaws.com/db-start-up-checker-service:latest

datadog:
  logs:
    enabled: true
