development:
  adapter: async

test:
  adapter: test

production:
  adapter: <%= ENV['CABLE_ADAPTER'] || 'postgresql' %>
  url: <%= ENV.fetch("REDIS_URL") { "redis://localhost:6379/1" } %>
  channel_prefix: greenlight_production