name: Mirroring

on: [push, delete]

jobs:
  to_codecommit:
    runs-on: ubuntu-latest
    env:
      CODECOMMIT_MIRROR_ENABLED: ${{ secrets.CODECOMMIT_MIRROR_ENABLED }}
    steps:
      - name: Checkout
        uses: actions/checkout@v2
        with:
          fetch-depth: 0

      - name: CodeCommit Mirroring
        if: contains(env.CODECOMMIT_MIRROR_ENABLED, 'true')
        uses: pixta-dev/repository-mirroring-action@v1
        with:
          target_repo_url:
            ${{ secrets.CODECOMMIT_TARGET_REPO_URL }}
          ssh_private_key:
            ${{ secrets.CODECOMMIT_SSH_PRIVATE_KEY }}
          ssh_username:
            ${{ secrets.CODECOMMIT_SSH_PRIVATE_KEY_ID }}

