---
name: Build and push Docker Image on Tag

on:
  push:
    tags:
      - '[0-9]+.[0-9]+.[0-9].*'
jobs:
  pre_build:
    runs-on: ubuntu-latest
    outputs:
      tag: ${{ steps.tag.outputs.tag }}
      suffix: ${{ steps.tag.outputs.suffix }}
    steps:
      - name: Filter Tag name
        uses: olegtarasov/get-tag@v2.1
        id: tag
        with:
          tagRegex: "(?<tag>[0-9]+.[0-9]+.[0-9])(?<suffix>.*)"
  build_and_push:
    needs: pre_build
    uses: hpi-schul-cloud/infra-tools/.github/workflows/build-and-push.yaml@master
    with:
      registry: ghcr.io
      image: dbildungsplattform/greenlight
      tag: ${{ needs.pre_build.outputs.tag }}
      prefix: v
      suffix: ${{ needs.pre_build.outputs.suffix }}
